Add identity provider
Concordium/concordium-ledger-app pull request #11
Opened 2021-07-29 13:36 UTC by shjortConcordium

## Purpose

Adds the Add Identity Provider update instruction
(Related to https://github.com/Concordium/concordium-desktop-wallet/pull/4)

## Changes

Adds the Add Identity Provider update instruction

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [] (If necessary) I have updated the CHANGELOG.

2021-07-30 05:55 UTC, orhoj commented
This should have an issue so that you can assign it to the R2 release. Otherwise it is not clear that this is included.

2021-07-30 07:37 UTC, orhoj requested changes

2021-07-30 07:37 UTC, orhoj commented on src/signAddIdentityProvider.c
> +#define P1_DESCRIPTION_LENGTH          0x01        // Used for both the message text and the specification URL.
The comments should state that it is for:
- Name
- Url
- Description

2021-07-30 07:37 UTC, orhoj commented on src/signAddIdentityProvider.c
> +        // We have received all bytes, continue to signing flow.
The comment does not match what is going to happen. This is also the case for other comments in the file, e.g. line 92 and line 103.

2021-07-30 07:37 UTC, orhoj commented on src/signAddIdentityProvider.c
> +        ctx->verifyKeyLength = U4BE(cdata, 0);
Calculate the length of the verification key instead of taking it as input.

2021-07-30 07:37 UTC, orhoj commented on src/signAddIdentityProvider.c
> +        uint8_t cdiVerifyKey[32];
I don't think you need this variable, you should be able to use `cdata` directly here.

2021-07-30 07:37 UTC, orhoj commented on src/signAddIdentityProvider.c
> +        "cdi Verify key",
Change this to:
```
CDI Verify Key
```
I am not sure if this needs to be something better when we update the terminology, but perhaps this is okay when it is a foundation transaction.

2021-07-30 07:38 UTC, orhoj commented
Also, please update the `CHANGELOG` with a line stating that this functionality has been added.

2021-07-30 07:45 UTC, shjortConcordium commented on src/main.c
> +#define INS_ADD_IDENTITY_PROVIDER 0x2D
Because I want Add Anonymity Revoker to be 0x2C, so that they have the same order as they updateType

2021-08-30 08:14 UTC, orhoj commented on src/signAddIdentityProvider.c
> +            (char *) global.signAddIdentityProviderContext.ipIdentity
Please fix all the indentation issues in this file.

2021-08-30 08:17 UTC, orhoj commented on src/signAddIdentityProvider.c
> +            // We received more bytes than expected.
The comment does match the check being made.

2021-08-30 08:18 UTC, orhoj commented on src/signAddIdentityProvider.c
> +#define P1_INITIAL              0x00
Align the hexadecimal numbers here.

2021-08-30 08:24 UTC, orhoj commented on doc/ins_add_identity_provider.md
> +| `0x2D` | `0x03` | `0x00` | `verify_key_length[uint32]`                                                                           | The length of the verify key.
This part is no longer relevant. Update the documentation to match the implementation.

2021-08-30 08:47 UTC, shjortConcordium commented on doc/ins_add_identity_provider.md
> +| `0x2D` | `0x03` | `0x00` | `verify_key_length[uint32]`                                                                           | The length of the verify key.
I updated it (removed this line and rewrote the description part).

2021-08-30 08:47 UTC, shjortConcordium commented on src/signAddIdentityProvider.c
> +            // We received more bytes than expected.
I updated the comment to match.

2021-08-30 08:47 UTC, shjortConcordium commented on src/signAddIdentityProvider.c
> +            (char *) global.signAddIdentityProviderContext.ipIdentity
I attempted to do this.

2021-08-30 09:32 UTC, orhoj commented on doc/ins_add_identity_provider.md
> +| `0x2D` | `0x04` | `0x00` | `verify_key[verify_key_length_bytes]`                                                          | The verify key bytes.
`p1 = 0x03` for verify key and `p1 = 0x04` for cdi verify key.

2021-08-30 09:33 UTC, orhoj commented on doc/ins_add_identity_provider.md
> +| `0x2D` | `0x03` | `0x00` | `verify_key_length[uint32]`                                                                           | The length of the verify key.
You fixed some of the issue, but it is still incorrect. I added a new comment for that.

2021-08-30 10:43 UTC, shjortConcordium commented on doc/ins_add_identity_provider.md
> +| `0x2D` | `0x04` | `0x00` | `verify_key[verify_key_length_bytes]`                                                          | The verify key bytes.
Yes, fixed it

2021-09-03 12:20 UTC, orhoj approved these changes

2021-09-06 06:44 UTC, merged