Verify address
Concordium/concordium-ledger-app pull request #33
Opened 2021-11-02 15:23 UTC by shjortConcordium

## Purpose

Add feature to allow user to verify their address.

## Changes

Add command to verify address.
Update nanox sdk to 2.0.

## Checklist

- [x] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.

2021-11-03 07:26 UTC, orhoj commented on src/main.c
> +#define INS_VERIFY_ADDRESS 0x36
I don't think that we have used `0x00` yet and I believe that would be nice to use here.

2021-11-03 07:41 UTC, orhoj commented on src/verifyAddress.c
> +   hmac_sha256.c
I believe we ended up not using this anyway, but instead used the internal functions provided by Ledger.

2021-11-03 08:20 UTC, orhoj commented on src/verifyAddress.c
> +void blsKeygen(const uint8_t *seed, size_t seedLength, uint8_t *dst, size_t dstLength) {
Please add documentation for the method and refer to the algorithm definition at https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-04#section-2.3.

2021-11-03 08:27 UTC, orhoj commented on src/verifyAddress.c
> +        cx_hash_sha256(salt, sizeof(salt), salt, sizeof(salt));
This should be the first operation in the loop. With this implementation you always end up hashing 1 more time than required.

2021-11-03 08:29 UTC, orhoj commented on src/verifyAddress.c
> +    uint8_t h[32];
Consider calling this `prk`  so that it matches the pseudo code.

2021-11-03 08:34 UTC, orhoj commented on src/verifyAddress.c
> +    uint8_t okm[l_CONST] = {0};
Why do we need this?

2021-11-03 09:10 UTC, orhoj commented on src/verifyAddress.c
> +    uint32_t keyDerivationPath[6] = {
You parse the key path above, but then use this hardcoded one instead?

2021-11-03 09:16 UTC, orhoj commented on src/verifyAddress.c
> +    parseKeyDerivationPath(cdata);
If we ask for anything but the initial credential, then we should fail.

2021-11-03 09:19 UTC, orhoj commented on src/verifyAddress.c
> +    uint8_t seed[64] = {0};
Why set it to `{0}`?

2021-11-03 09:29 UTC, orhoj commented on src/verifyAddress.c
> + * Change the interpretation of the given byte array as a utf8 string. The output should have double the size of the input.
We are intepreting it as the UTF-8 of the hex encoding of the bytes.

2021-11-03 09:31 UTC, orhoj commented on src/verifyAddress.c
> + * N.B. Added to duplicate error in Concordium desktop wallet.
Maybe relax this text a little bit. An error would indicate something we would want to fix later. 
```
Note that the bytes could be used directly, but due to keys having already been derived with this interpretation, we have to stick with it.
```

2021-11-03 09:31 UTC, orhoj commented on src/verifyAddress.c
> +    uint32_t cred_counter = keyPath->rawKeyDerivationPath[6];
Use camelCase.

2021-11-03 09:33 UTC, orhoj commented on src/verifyAddress.c
> +void blsKeygen(const uint8_t *seed, size_t seedLength, uint8_t *dst, size_t dstLength) {
I would expect this to be used when we extract PRF-keys and IdCredSec as well.

2021-11-03 09:48 UTC, orhoj commented on src/verifyAddress.c
> +    getPrivateKey(keyDerivationPath, 6, &seed_t);
Usage of private keys should be in a try-catch block.

2021-11-04 08:25 UTC, shjortConcordium commented on src/verifyAddress.c
> + * Change the interpretation of the given byte array as a utf8 string. The output should have double the size of the input.
Removed this.

2021-11-04 08:25 UTC, shjortConcordium commented on src/verifyAddress.c
> + * N.B. Added to duplicate error in Concordium desktop wallet.
Removed this.

2021-11-04 08:26 UTC, shjortConcordium commented on src/verifyAddress.c
> +   hmac_sha256.c
Yes we did.

2021-11-04 08:50 UTC, shjortConcordium commented on src/verifyAddress.c
> +    uint8_t okm[l_CONST] = {0};
We don't

2021-11-04 08:50 UTC, shjortConcordium commented on src/verifyAddress.c
> +        cx_hash_sha256(salt, sizeof(salt), salt, sizeof(salt));
I've tried to do this.

2021-11-04 09:48 UTC, shjortConcordium commented on src/verifyAddress.c
> +    uint8_t okm[l_CONST] = {0};
I have removed the variable (because we only need `sk`), but setting it to zero had a purpose, because we check that the variable is 0.

2021-11-04 09:59 UTC, shjortConcordium commented on src/verifyAddress.c
> +    uint8_t seed[64] = {0};
It was unnecessary. (removed it)

2021-11-04 11:33 UTC, shjortConcordium commented on src/verifyAddress.c
> +void blsKeygen(const uint8_t *seed, size_t seedLength, uint8_t *dst, size_t dstLength) {
I have added an endpoint for extracting the private keys, not as seeds.

2021-11-04 11:35 UTC, shjortConcordium commented on src/verifyAddress.c
> +    parseKeyDerivationPath(cdata);
I don't understand this?
The ledger doesn't know anything about a credential's initial'ness.

2021-11-18 14:40 UTC, orhoj commented on doc/export_private_key.md
> +If P2 = 0x01, the exported key are derived using SLIP10 for ed25519.
```suggestion
If P2 = 0x01, the exported keys are derived using SLIP10 for ed25519. 
```

2021-11-18 14:43 UTC, orhoj commented on doc/export_private_key.md
> +These can be used as the key seed for the KeyGen algorithm for generating BLS12-381 private keys.
they have to be used for that, and nothing else.

2021-11-18 14:45 UTC, orhoj commented on doc/export_private_key.md
> +| `0x00` | `0x01` | `identity[uint32]` | Export of PRF key |
I think it is a good idea to make it more explicit that this is the key seed.
```suggestion
| `0x00` | `0x01` | `identity[uint32]` | Export of PRF key seed for the BLS12-381 KeyGen algorithm |
```

2021-11-18 14:49 UTC, orhoj commented on rust_tests/src/bin/export_private_key.rs
> +    let prf_seed = &result[..64];
`prf_seed` and `id_cred_seed` are not seeds in this test, but actually the keys.

2021-11-18 14:54 UTC, orhoj commented on doc/export_private_key.md
> +If P2 = 0x01, the exported key are derived using SLIP10 for ed25519.
We should probably state here (and in the corresponding code) that exporting the key seeds should not be used, i.e. it is deprecated and only still there for legacy reasons.

2021-11-18 14:59 UTC, orhoj commented on src/util.h
> + * Field modulus associated with BLS12-381
This is not the field modulus, but the size (or order) of the subgroup.

2021-11-18 15:03 UTC, orhoj commented on src/exportPrivateKey.c
> +// Allow the user to decline exporting the private keys.
This was an old TODO. I don't think we want to keep it :smile:

2021-11-19 08:25 UTC, orhoj commented on src/verifyAddress.c
> +    // Inverse of prf + cred_counter is our prf_exp
In the rust code `prf_exp` is called `cred_id_exponent`.

2021-11-19 08:38 UTC, orhoj commented on src/verifyAddress.c
> +end:
Why do you need this?

2021-11-19 09:00 UTC, orhoj commented on src/util.c
> +    if (dstLength < BLS_KEY_LENGTH) {
This should be moved to the start of the function.

2021-11-19 09:04 UTC, orhoj commented on src/util.c
> +    memmove(dst, sk + l_CONST - BLS_KEY_LENGTH, BLS_KEY_LENGTH);
Leave a comment stating why we skip the first 16 bytes here.

2021-11-19 09:05 UTC, orhoj requested changes
Please change the stuff above.

2021-11-29 14:06 UTC, shjortConcordium commented on src/verifyAddress.c
> +end:
if there is an error then CX_CHECK jumps down to this label.

2021-11-29 14:47 UTC, orhoj commented on src/verifyAddress.c
> +    // Inverse of prf + cred_counter is our prf_exp
The comments still refer to `prf_exp`.

2021-12-13 08:03 UTC, orhoj approved these changes

2021-12-14 08:48 UTC, merged