Add register data transaction
Concordium/concordium-ledger-app pull request #36
Opened 2021-12-03 09:44 UTC by shjortConcordium

## Purpose

Add support for the register data transaction.

## Changes

Added the register data transaction, and a test for it.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

2021-12-10 13:04 UTC, orhoj commented on src/globals.h
> +        signRegisterData_t signRegisterData;
This is not a transfer with memo.

2021-12-10 13:19 UTC, orhoj commented on src/globals.h
> +        signRegisterData_t signRegisterData;
It looks like you are doing this as we need to parse the data in a similar way to a memo, but this is too hacky. If you want to share stuff, then the memo code should be generalized and then used by both. But this should not be put under something called "memo" when it is not a memo.

2021-12-10 13:29 UTC, orhoj commented on src/signRegisterData.c
> +        ctx->dataLength = U2BE(cdata, 0);
Add validation on the data length. I believe it is restricted to `256`  bytes, so anything greater than that is invalid.

2021-12-10 13:34 UTC, orhoj commented on tests/src/registerData.test.ts
> +test('[NANO X] Sign a register data transaction', setupZemu('nanox', registerDataTest('nanox_register_data', 3)));
Add negative tests for submitting too too much data.

2021-12-10 13:36 UTC, orhoj requested changes
.

2021-12-15 11:49 UTC, shjortConcordium commented on src/globals.h
> +        signRegisterData_t signRegisterData;
I can rename all the memo code to say data or something, but the register data's data has the same specification as a memo. (It would be simpler to just rename the transaction to registerMemo)

2021-12-16 08:20 UTC, shjortConcordium commented on src/globals.h
> +        signRegisterData_t signRegisterData;
I have renamed the memo files to `displayCbor`, as that it what it does.
I have renamed this struct to `transactionWithDataBlob`, with a CborContext.

2021-12-17 08:59 UTC, orhoj commented on src/displayCbor.h
> +} CborContext_t;
All our other structs are named as camelCase.

2021-12-17 09:00 UTC, orhoj commented on src/displayCbor.c
> +    {"Memo", (char *) global.withDataBlob.cborContext.display});
Does this mean that it will also show up as "Memo" when doing a register data transaction?

2021-12-17 09:02 UTC, orhoj commented on src/displayCbor.c
> -    if (ctx->memoLength > MAX_MEMO_SIZE) {
Is it no longer relevant to check the max length here?

2021-12-17 09:08 UTC, orhoj commented on src/displayCbor.c
> +    {"Memo", (char *) global.withDataBlob.cborContext.display});
It seems like the Data one has its own UI component. This component could have a memo specific name instead as it is only used for that. We can also just keep it as is.

2021-12-17 09:08 UTC, orhoj commented on src/displayCbor.c
> -    if (ctx->memoLength > MAX_MEMO_SIZE) {
I see that it is checked elsewhere now.

2021-12-17 13:07 UTC, shjortConcordium commented on src/displayCbor.c
> +    {"Memo", (char *) global.withDataBlob.cborContext.display});
Changing it!

2022-01-10 06:50 UTC, orhoj approved these changes

2022-01-10 08:03 UTC, merged