Ledger fixes
Concordium/concordium-ledger-app pull request #73
Opened 2023-01-31 08:39 UTC by shjortConcordium

## Purpose

Fix stuff based on feedback from ledger + cleanup unnecessary flows. 

## Changes

- Add accept/reject in “compare” screen.
- Add CCD/unit to transfers
- Merge flows in identity issuance
- Remove chain updates
- Remove old baker flows
- allow paths used by browser wallet

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

2023-02-02 11:02 UTC, bisgardo requested changes
Please remove the `rust_tests` that are no longer relevant.

2023-02-02 11:05 UTC, bisgardo commented
It's not that big of a deal in this PR but I think that in general we should strive to separate formatting changes and other trivialities (like bulk deletion) from more complex changes.

2023-02-02 13:12 UTC, shjortConcordium commented on src/signPublicInformationForIp.c
>      sendSuccessNoIdle(),
I checked at least with our other flows, and there we have a "continue" screen, so I've added that.

2023-02-02 13:12 UTC, shjortConcordium commented on src/signPublicInformationForIp.c
> +    &ux_sign_public_info_for_ip_public_key_0_step,
Yeah, good catch. I should've created a new step without the callback, but with the continue screen, we don't a version with callback. 
(I changed the name to `ux_sign_public_info_for_ip_display_public_key`)
(Also renamed the one for threshold to `ux_sign_public_info_for_ip_display_threshold`)

2023-02-02 18:36 UTC, shjortConcordium commented on src/getPublicKey.c
>      {&C_icon_validate_14, "Public key", (char *) global.exportPublicKeyContext.display});
Yeah, the display is a bit "compressed", but it should be clear when used together with the wallet.
We could add an issue for this, but I don't think we need to fix it here. :thinking:

2023-02-03 08:38 UTC, bisgardo approved these changes

2023-02-03 09:00 UTC, merged