Governance app
Concordium/concordium-ledger-app pull request #89
Opened 2023-09-05 15:26 UTC by shjortConcordium

## Purpose

Make an app that allows signing the chain updates, which was removed from the main app.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

2023-09-07 11:02 UTC, orhoj requested changes

2023-09-07 11:02 UTC, orhoj commented on .github/workflows/build-pipeline.yml
> +        name: Compile Governance app for Nano S
We can also sideload for nano s plus.

2023-09-07 11:07 UTC, orhoj commented
The `menu` should also be able to be shared (only the text of the UI is different). The main file is also basically duplicated.

2023-09-07 14:55 UTC, shjortConcordium commented on governance-app/src/glyphs.c
> +#include "glyphs.h"
They are, but I guess I added them before I ignored them, they will be removed

2023-09-08 13:40 UTC, shjortConcordium commented on governance-app/src/globals.h
> +#define CONCORDIUM_PURPOSE   1105
Yes but the "mess to fix" to "reduction of duplication" is too rough :upside_down_face:

2023-09-11 09:16 UTC, orhoj requested changes

2023-09-13 19:26 UTC, shjortConcordium commented on governance-app/src/globals.c
> +bolos_ux_params_t G_ux_params;
I don't think we usually do this? :thinking:

2023-09-13 19:27 UTC, shjortConcordium commented on Makefile.common
> +COMPILE_FLAGS = -DAPPNAME=\"$(APPNAME)\"
I didn't realise it could be done like that. :thinking:

2023-09-18 14:15 UTC, orhoj approved these changes

2023-09-19 08:09 UTC, merged